language: generic
sudo: required 
servies:
    - docker

before_install:
    - docker build -t nagavamsi/react-test -f./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test  

after_sucess:
    - docker build -t nagavamsi/multi-client ./client
    - docker build -t nagavamsi/multi-nginx ./ngnix 
    - docker build -t nagavamsi/multi-server ./server
    - docker build -t nagavamsi/multi-worker ./worker   
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them 
     - docker push nagavamsi/multi-client 
     - docker push nagavamsi/multi-nginx
     - docker push nagavamsi/multi-server
     - docker push nagavamsi/multi- worker