sudo: required
services:
    - docker

before_install:
    - docker build -t nagavamsi/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true nagavamsi/react-test npm test     

after_success:   
    - docker build -t nagavamsi/multi-client ./client
    - docker build -t nagavamsi/multi-nginx ./nginx
    - docker build -t nagavamsi/multi-server ./server
    - docker build -t nagavamsi/multi-worker ./worker 
    # log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    # take those images and push them to dockerhub
    - docker push 1813354/multi-client 
    - docker push 1813354/multi-nginx
    - docker push 1813354/multi-server 
    - docker push 1813354/multi-worker

deploy:
    edge: true 
    provider: elasticbeanstalk 
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-499743792767
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


        


